import type { SimStats, SimSnapshot } from './types';

const mockSimAPI = {
  start: () => {},
  pause: () => {},
  reset: () => {},
  setTimeScale: (_m: number) => {},
  setScenario: (_name: 'baseline' | 'heatwave' | 'polluted') => {},
  toggleModule: (_name: string) => {},
  toggleAblation: (_name: string) => {},
  exportData: () => {},
  mountWorldCanvas: async (_canvas: HTMLCanvasElement) => {},
  mountBrainCanvas: async (_canvas: HTMLCanvasElement) => {},

  getStats: (): SimStats => ({
    energy: 142,
    hunger: 0.34,
    reward: 1,
    correctEats: 47,
    toxicEats: 8,
    predatorHits: 3,
    nightInShelter: 0.81,
    currentStep: 4821,
    currentTrial: 2,
    nutritionPhase: 'BC',
    daylight: 0.72,
    speed: 1.24,
    position: { x: 42.1, y: 67.3 },
    heading: 1.32,
    activityCost: 12.4,
    learningEnabled: true,
    stepsToNightfall: 127,
    stepsToNutritionRotation: 342,
    eventLog: [
      '[t=4800] Nutritious eat +40',
      '[t=4200] Toxic eat −25',
      '[t=3100] Entered shelter',
      '[t=2031] Predator hit! −50',
      '[t=1842] Nutrition: AB → BC',
    ],
    energyHistory: Array.from({ length: 500 }, (_, i) => 100 + 50 * Math.sin(i / 30)),
    correctEatHistory: Array.from({ length: 500 }, (_, i) => 60 + 20 * Math.sin(i / 40)),
    activityCostHistory: Array.from({ length: 500 }, (_, i) => 10 + 5 * Math.sin(i / 20)),
    predatorHitSteps: [820, 2031, 4150],
    chemicalHistory: Array.from({ length: 100 }, (_, i) => 0.5 + 0.4 * Math.sin(i / 6)),
    acousticLHistory: Array.from({ length: 100 }, (_, i) => 0.3 * Math.sin(i * 0.295 + 0.1)),
    acousticRHistory: Array.from({ length: 100 }, (_, i) => 0.3 * Math.sin(i * 0.295 - 0.1)),
    neuronCount: 164,
    connectionCount: 847,
    avgWeightMagnitude: 0.42,
    M1: 0.23,
    M2: 0.07,
    trialResults: [],
    aggregateScores: null,
  }),

  getSnapshot: (): SimSnapshot => ({
    neurons: [],
    connections: [],
    activityThisStep: 12.4,
    neuronCount: 164,
    moduleNeuronCounts: {
      chemo: 52,
      predator: 26,
      shelter: 22,
      value: 14,
      motor: 62,
    },
    M1: 0.23,
    M2: 0.07,
  }),
};

export default mockSimAPI;
